# fly.toml app configuration file generated for christmas-draw-app on 2024-12-02T17:12:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'christmas-draw-app'
primary_region = 'ams'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[mounts]
source = "tinydb_vol"
destination = "/app/db"
initial_size = "1gb"    # optional - the size of the volume created on first deploy

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 512
